version: '3'

services:
  php:
    build: ./build/php
    container_name: php
    restart: always
    volumes:
      - ~/work:/work:rw
      - ./work/components/php/config/php.ini:/usr/local/etc/php/php.ini:ro
      - ./work/components/php/config/php-fpm.conf:/usr/local/etc/php-fpm.d/www.conf:rw
      - ./work/components/php/log:/var/log:rw
      - ./work/components/php/start.sh:/home/start.sh:rw
      - ./work/components/php/.composer:/root/.composer:rw
      - ./www:/www:rw
    privileged: true
    networks:
      - net_php
      - net_redis
      - net_mysql
      
  redis:
      image: redis:latest
      container_name: redis
      ports:
        - "6379:6379"
      volumes:
        - ./work/components/redis/config/redis.conf:/usr/local/etc/redis/redis.conf:ro
        - ./work/components/redis/log/redis.log:/var/log/redis/redis.log:rw
      restart: always
      privileged: true
      networks:
        - net_redis

  nginx:
      image: nginx:alpine
      container_name: nginx
      ports:
        - "80:80"
      volumes:
        - ~/work:/work:rw
        - ./work/components/nginx/config/nginx.conf:/etc/nginx/nginx.conf:ro
        - ./work/components/nginx/config/conf.d:/etc/nginx/conf.d:ro
        - ./work/components/nginx/log:/var/log/nginx:rw
        - ./www:/www:rw
      command: [nginx-debug, '-g', 'daemon off;']
      restart: always
      privileged: true
      networks:
        - net_php
  mysql:
    image: mysql:latest
    container_name: mysql
    ports:
      - "3306:3306"
      - "33060:33060"
    volumes:
      - ./mysql/conf.d:/etc/mysql/conf.d
      - ./mysql/data:/var/lib/mysql
    restart: always
    networks:
      - net_mysql
    environment:
      MYSQL_ROOT_PASSWORD: "z283779377g"

networks:
  net_php:
  net_redis:
  net_mysql: